### ISSUE TITLE
Get BTCPay Server to work with Wownero (15,000 WOWX)

### ISSUE THREAD

**Issue by wowario** [wowario/meta#15]
https://docs.btcpayserver.org/Docker/
https://github.com/btcpayserver/btcpayserver-doc/issues/815

**Comment by alexeyneu** [comment]
but what is WOWX?

**Comment by wownerox** [comment]
WOWX is a new utility/governance token that will be launched on the [Avalanche network](https://www.avax.network/) on 1 January 2022
