### ISSUE TITLE
Fork CakeWallet get it working with Wownero for iOS (30,000 WOWX)

### ISSUE THREAD

**Issue by wowario** [wowario/meta#17]
https://github.com/cake-tech/cake_wallet

**Comment by alexeyneu** [comment]
i can do this

**Comment by wownerox** [comment]
awesome sauce. wownero is basically the same as monero, but some minor changes here and there and we are already rolling with Bulletproofs+ https://git.wownero.com/wownero/wownero

**Comment by rottenstonks** [comment]
@alexeyneu You can do this... but we haven't heard any news or further comments from you for a couple weeks. Any updates or comments on this, sir? Thanks.
