### ISSUE TITLE
Help Establish WowneroX Decentralized Autonomous Organization (DAO) (50,000 WOWX)

### ISSUE THREAD

**Issue by wowario** [wowario/meta#4]

**Comment by lalanza808** [comment]
I have some direct experience implementing dApps and interfaces w/ contract interactions. I can try and take this on.

**Comment by wownerox** [comment]
cool. having a voting mechanism would help decentralize the decision making process.

I've included the [ERC20Votes](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20Votes) extension to the [WOWX contract](https://github.com/wownerox/meta/blob/main/contracts/wowx.sol).

for reference, there is a Voting dApp on Avalanche tutorial [here](https://docs.avax.network/build/tutorials/tutorials-contest/evoting-avalanche-dapp/README)

**Comment by wownerox** [comment]
instead of a basic voting DApp, it would be much better to have a general DAO for WowneroX governance
